language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch
  - "pypy"
  - "pypy3"
# command to install dependencies
install: "pip install -r test-requirements.txt"
# command to run tests
script: python -m unittest discover
after_success:
  - coverage run -m unittest discover
  - codecov
